### ISSUE TITLE
USER STORY: Publish a poll

### ISSUE THREAD

**Issue by EdsonSMartins** [EdsonSMartins/love-running#3]
In order to ** ensure timely publication and closure of polls ** as an **administrator**, I can **define the duration for each poll, allowing me to specify start and end dates**
.
## Acceptance Criteria
- the poll should have a timer
- once response submitted poll should not be available to same user 

## Tasks
- [ ] Set up html structure.
- [ ] Set up function code to create timer and handle submission.
- [ ] Set up function code to check if user has already submitted the poll.
